# This is a basic workflow to help you get started with Github Actions
 
name: Workflow
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install Libraries
        run: |
          R -e 'install.packages(c("sqldf","rodbc","stringr","dplyr"))'
          R -e 'install.packages("rvest")'
          R -e 'install.packages("xml2")'   

      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Setting the Mkdir - File directory
        run: mkdir -p Output
        
      - name: Run R script - Extract & Transformation
        run: Rscript Currency.R  
 
      - name: Loading process - Output
        uses: actions/upload-artifact@v4
        with:
            name: Output file
            path: Output/Currency.csv
            retention-days: 2
